#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below.

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
#
#/ command: chart-mate:bumpver: "change versions of components"
#/ usage: rerun chart-mate:bumpver [options]

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh bumpver || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -eo pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting
# one the corresponding option variables.

rerun_options_parse "$@"

load-config

helm doctor

log-info "Adding deis helm repo..."
helm repo add deis https://github.com/deis/charts.git || true

log-info "INJECTING VERSIONS!"
log-info "-------------------"
bumpver-if-set "deis-logger" "fluentd" "${FLUENTD_GIT_SHA}"
bumpver-if-set "deis-logger" "logger" "${LOGGER_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "builder" "${BUILDER_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "minio" "${MINIO_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "postgres" "${POSTGRES_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "registry" "${REGISTRY_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "router" "${ROUTER_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "controller" "${CONTROLLER_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "slugbuilder" "${SLUGBUILDER_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "slugrunner" "${SLUGRUNNER_GIT_SHA}"
bumpver-if-set "${WORKFLOW_CHART}" "dockerbuilder" "${DOCKERBUILDER_GIT_SHA}"
log-info "-------------------"
rsync-no24 -av . "${HELM_HOME}/cache/deis/" > /dev/null
